(******************************************************************)
(* DO NOT EDIT THIS FILE                                          *)
(******************************************************************)

let check_interp_expr : string -> string = Main.interp_expr

module type AuthorsSig = sig
  val hours_worked : int list
end

module AuthorsCheck : AuthorsSig = Authors
